name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [^14.18.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
        # Build and test the project, then
        # deploy
      run: |
        npm install
        npm run build --if-present
      env:
        CI: false
      # env:
      #   DB_Key: ${{ secrets.DB_Key }}
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [^14.18.0]
    steps:
      - name: Download articats
        uses: actions/download-artifact@v2
        with:
          name: production-files
      - uses: actions/checkout@v2
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          FIREBASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
